### ISSUE TITLE
your idea might be patented by tecnica

### ISSUE THREAD

**Issue by hstarmans** [hzeller/ldgraphy#10]
Look at article https://www.fabbaloo.com/news/looking-at-tecnicas-unusual-sls-optical-system

They use the same mirror system as you do, claim it's novel without mentioning your work.
Are you familiar with this!?

**Comment by hzeller** [comment]
Not familiar with that. That article does not mention any patents.

But since it is documented [here](https://github.com/hzeller/ldgraphy/blob/master/design.md#cone-mirror-arc-exposure) already it certainly can't be patented because prior art.

**Comment by hstarmans** [comment]
Henner,

Prior art does not make it impossible to get a patent.
You r right that it does invalidate the patent *but *legal costs / risks
are very high to invalidate it

An example is given by Bunnie ( Andrew "bunnie" Huang is an American
researcher and hacker, who holds a Ph.D in electrical engineering from MIT
and is the author of the freely available 2003 book Hacking the Xbox)
https://patentpandas.org/stories/crowdfunding-backer-patented-my-project


The method of tecnica is slightly different from yours, they use a
different rotating mirror (not a polygon one) see their website
https://tecnica.com/

[image: afbeelding.png]


Their patent is US10473915B2 and US9435998B1, as you can see they don't use
a polygon mirror but a mirrror with some angle.

[image: afbeelding.png]
Conclusion;
  I might have rung the alarm bell too soon, but it is very close to your
work so might be good to add to your project as a reference or be aware of
non the less.
  I looked into the legal claims and it does seem different in that they
hit the first reflector along the rotation axis and you hit it perpendical
to the rotational axis.
  They might also be able to provide a mirror you need for your project


Regards,

Rik




Am Mo., 9. Aug. 2021 um 20:43 Uhr schrieb Henner Zeller <
***@***.***>:

**Comment by hstarmans** [comment]
As i see it, the main issue of ldgraphy is the cross scan error. Each facet is slightly different which gives an error orthogonal to the scanline. Tecnica fixed this by using only one facet. The manufacturing requirements of the curved mirror also decrease as you always hit this mirror at the same location. Even if it is not an arc it is constant. The duty cycle can be increased by using a non uniform rotation speed or completing the arc to a circle. If it is a circle or a large arc, the best way to hit the mirror is along the rotational axis.
In your description you use an image where the polygon mirror is hit orthogonal to rotation, not perpendicular.  This variation is not under patent.

**Comment by hstarmans** [comment]
Possible variations;
 - rotate an array of light sources at the point you now rotate the polygon mirror
 - You can still hit ortogonal to the rotation axis
 Tecnica did not patent this
    Tilt the beam slightly upwards(so facets of polygon mirror are tilted and it is a pyramidal polygon mirror) you can then still create a large arc but… with one source you can not create a circle.. you could put more sources in a ring around the center and sell this as an advantage
