### ISSUE TITLE
Not an issue, but a (stupid) question

### ISSUE THREAD

**Issue by Pepetruen0** [hzeller/ldgraphy#3]
Hi, I'm seeing that the laser driver has a note stating "there is now a cap accross R3." As I'm a newbie and English is not my primary language, can I have a brief explanation of what this means? Also, what size capacitor do I need to use for this?

Thanks.

**Comment by hzeller** [comment]
This means that there needs to be an additional capacitor in parallel to `R3`, which has not been reflected yet in the schematic or printed circuit board.
I have fudged the capacitor in with what I had lying around, I think it was around 100pF.

**Comment by Pepetruen0** [comment]
Wait, when you say "fudged" do you mean "I got away with" or "totally destroyed"? Just to be sure.
Also, would something like this work?
![capacitor](https://user-images.githubusercontent.com/10561579/30040308-87b3dc12-91ab-11e7-9f1c-0283efcb18d8.jpg)

**Comment by hzeller** [comment]
'fudged' means that I choose the value without much calculation after having measured the outcome on an oscilloscope. I hacked it into the existing board by just soldering the capacitor on top of the R3. It works well.

Not sure what you want to do with your circuit above, but the 100pF needs to be across `R3` not `R2`.

**Comment by Pepetruen0** [comment]
Whoops, my bad. I meant something like this, would it work?

![cap](https://user-images.githubusercontent.com/10561579/30067050-b32b5128-9227-11e7-98a6-ef60da9d6e84.jpg)

**Comment by hzeller** [comment]
Yeah, this looks good. The value is somehwere in the order of 22pF to 100pF. They will essentially suppress unstable behavior like this:

https://plus.google.com/u/0/+HennerZeller/posts/g9reVCg4bnE

**Comment by Pepetruen0** [comment]
Awesome, thank you so much for your patience!
