### ISSUE TITLE
Python port

### ISSUE THREAD

**Issue by hstarmans** [hzeller/ldgraphy#7]
Hey Henner,

I started porting your code to Python. Progress is available here [python port](https://github.com/hstarmans/ldgraphy/tree/master/scripts/pru_tests). In specific, the stabilizer folder. I have been able to get my polygon stable with your code for the firestarter board. I did not need a Schmitt trigger. The signal looks quite crisp without it.
I hope the Python port will make your assembly driver code more accessible for other developers. In addition, I am not very experienced with C++ so wanted to ditch it anyway :-).

Best,

Rik

**Comment by hzeller** [comment]
Cool, Have fun!
(I'll stick with C++, it is much easier to read, write and deal with than Python, which I find really very inaccessible actually)
